2023-07-14 10:24:12,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=th0198&password=c607d58e3618832f937d80d500a6046c
    响应体:{'code': 20000, 'data': {'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODkzMDUwNTMsInVzZXJJZCI6MTA3MDIsInVzZXJuYW1lIjoidGgwMTk4In0.dUTVT2r4sutVzBm9SMZmy0CVnlmpcVHPkHLsbDwyKHk'}, 'flag': '松勤教育', 'msg': '成功', 'success': False}
2023-07-14 10:24:12,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

2023-07-14 10:24:12,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=th0198&password=d41d8cd98f00b204e9800998ecf8427e
    响应体:{'code': 9999, 'data': '', 'flag': '松勤教育', 'msg': '输入的密码错误!', 'success': False}
2023-07-14 10:24:12,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

2023-07-14 10:24:12,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=&password=c607d58e3618832f937d80d500a6046c
    响应体:{'code': 9999, 'data': '', 'flag': '松勤教育', 'msg': '该用户不存在!', 'success': False}
2023-07-14 10:24:12,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

2023-07-14 10:24:12,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=&password=d41d8cd98f00b204e9800998ecf8427e
    响应体:{'code': 9999, 'data': '', 'flag': '松勤教育', 'msg': '该用户不存在!', 'success': False}
2023-07-14 10:24:12,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

2023-07-14 10:24:13,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=th0198&password=68053af2923e00204c3ca7c6a3150cf7
    响应体:{'code': 9999, 'data': '', 'flag': '松勤教育', 'msg': '输入的密码错误!', 'success': False}
2023-07-14 10:24:13,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

2023-07-14 10:24:13,baseAPI(line:54),INFO|模块名:Login,接口名:login'
    请求的url:http://42.192.62.8:8082/account/sLogin
    请求方法:POST
    请求体:username=abcde&password=c607d58e3618832f937d80d500a6046c
    响应体:{'code': 9999, 'data': '', 'flag': '松勤教育', 'msg': '该用户不存在!', 'success': False}
2023-07-14 10:24:13,apiAssert(line:44),ERROR|Traceback (most recent call last):
  File "E:\deliverySystem\common\apiAssert.py", line 41, in api_assert
    raise AssertionError('请输入正确的断言情况')
AssertionError: 请输入正确的断言情况

